[workspace]
authors = ["Don Setiawan <landungs@uw.edu>"]
channels = ["conda-forge"]
name = "workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
get-hpyx = { cmd = "git submodule --init -- current-projects/HPyX" }
remove-hpyx = { cmd = "git submodule deinit -- current-projects/HPyX" }

[dependencies]
